version: "3"
services:
#######Below is the flask microservice part of ports and volumes
  flask-microservice:
    build:
      context: ./flask-microservice
      dockerfile: Dockerfile
    ports:
      - 2727:2727
    volumes:
      - ./flask-microservice:/app

########Below is the laravel microservice part of ports and volumes
  laravel-microservice:
    build:
      context: ./laravel-microservice
      dockerfile: Dockerfile
    ports:
      - 2728:2728
    volumes:
      - ./laravel-microservice:/var/www/html

########Below is the react microservice part of ports and volumes
  react-microservice:
    build:
      context: ./react-microservice
      dockerfile: Dockerfile
    ports:
      - 2729:2729
    volumes:
      - ./react-microservice:/app

